meta:
    site_title: "o's Blog"
    site_subtitle: "To study hard..."
    site_language: "en"
    author:
        full_name:4
        short_name: O
        name: O
        email: naneitou@qq.com

#baseurl: /base

markdown: kramdown

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: ypchenstory

lsi: false



