permalink: /:year/:month/:day/:title.html
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
index_path : /index.html

title : "lorazepam's blog"
tagline: Site Tagline
author :  
  name : lorazepam
  email : naneitou@gmail.com
  github : s474959009
  
BASE_PATH : false
ASSET_PATH : false
analytics :
   provider : google 
   google : 
       tracking_id : 'UA-31769544-1'
   getclicky :
     site_id : 
   mixpanel :
       token : '_MIXPANEL_TOKEN_'